# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  resolvers:
    default:
      web_path:
        web_root: "%kernel.project_dir%/public"
        cache_prefix: "media/cache"

  #Définition de l'ensemble des filtres

  filter_sets:
    # Le filtre header_logo servira à dimensionner la taille du logo dans l'entête du site
    header_logo:
      quality: 85
      filters:
        thumbnail: { size: [100, 50], mode: inset }
    resize_height_640:
      filters:
        thumbnail:
          size: [null, 640] #La largeur est définie sur null pour que l'image garde son ratio d'aspect original et la hauteur est définie sur 640 pixels
          mode: inset
          allow_upscale: false
